name: My Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Hello World!"
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - run: tree

  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    env: job2
    steps:
      - run: echo "Hello World"
